### PR TITLE
feat(new documentation): New gitbook documentation

### PR DESCRIPTION
**Pull request by lucasrose**
Updated documentation to 0.13.3 and switched from Jekyll to Gitbook

### CODE REVIEW

**Comment by lucasrose** [comment]
Changes
- Switched from Jekyll to GitBook
- Updated documentation to 0.13.3
- Added documentation instructions
- Custom Styling
- `_book` directory serves the book
- Added `scripts/update_gitbook` to install dependencies, serve js, and build site

screen shot 2016-07-25 at 2 24 52 pm

screen shot 2016-07-25 at 2 27 54 pm

screen shot 2016-07-25 at 2 26 07 pm

**Comment by adampickeral** [comment]
do all the files in `_site/`/`_book` need to be kept in version control, or does the github pages engine automatically generate them for you? (i suspect that they might, although i've never confirmed this)

**Comment by lucasrose** [comment]
@adampickeral so from what it looked like to me if we want to host the docs where they were we need the _book directory, if we separate the documentation and have that on gitbook's site, then it will be auto generated

**Comment by akrikos** [comment]
Notes from in person talk:
* Components links in navigation flicker to the right after page load on the js based pages (Components and each individual component page)
* Popover and tooltips are incorrectly placed on page in examples

Otherwise the content looks nice.

**Pull request closed without merging**
