### PR TITLE
enchancement #68

### PR DESCRIPTION
**Pull request by underbyte**
upgrade karma and all karma dep
#68

### CODE REVIEW

**Comment by adampickeral** [comment]
exact dependencies please.

better commit message:
```
chore(test upgrade): upgrade karma and jasmine

resolves issue #68
```

**Comment by bradgignac** [comment]
For libraries, it's nice to have flexible dependencies so you don't force every consumer to a single version.

**Comment by adampickeral** [comment]
interesting. these are all devDependencies, so it shouldn't matter for this, right?

on that point, I do worry about breaking changes with dependency upgrades when we don't specify an exact version, but if it's best practice for libraries to be more flexible, then we can do that with the other dependencies.

**Comment by j00k** [comment]
Ideally everything but *major* releases should be backwards compatible but I'm not saying everyone npm contributor follows that guideline :smile_cat:

**Comment by rogeriochaves** [comment]
:ship: :it:

**Comment by bradgignac** [comment]
@adampickeral @j00k Consumers of any library should _always_ use `npm shrinkwrap` to lock their entire dependency tree.

**Comment by bradgignac** [comment]
@adampickeral Dev dependencies matter because I'm pretty sure `npm install` installs them by default.

**Comment by bradgignac** [comment]
@adampickeral @j00k One other thing: npm3 supports flattening the dependency tree, so you don't end up with multiple versions of the same library in use. This is great for server-side, but it is _very important_ for client-side builds to make sure you don't unnecessarily bloat your builds. When flattening dependency trees, it's very important to allow flexible versioning because the likelihood of a conflict is much higher.

**Comment by adampickeral** [comment]
i'm pretty sure `devDependencies` don't work that way (what would be the point?). they only get installed if you run `npm install` from the root of that library package.

i tested this out by requiring `canon-react` as a dependency, running `npm install`, and ensuring that none of its `devDependencies` were installed (not alongside `canon-react` in `node_modules` nor in `node_modules` within `canon-react`)

**Comment by bradgignac** [comment]
@adampickeral :ok_hand:

**Comment by adampickeral** [comment]
:+1:

**Pull request merged**
