### PR TITLE
fix(propTypes): use accurate propTypes

### PR DESCRIPTION
**Pull request by willcumbie**
Remove instances where 'children' is specified unnecessarily and 'className' is specified as an array rather than a string.

### CODE REVIEW

**Comment by underbyte** [comment]
looks a lot better thanks for the fix!

**Comment by wpwood** [comment]
@willcumbie Is 'any' right here for children? There's a 'node' PropType that is described as "Anything that can be rendered: numbers, strings, elements or an array (or fragment) containing these types."

**Comment by willcumbie** [comment]
@wpwood `node` sounds better, I'll try that.

**Comment by adampickeral** [comment]
:+1:

**Pull request merged**
