### PR TITLE
Upgrade tether

### PR DESCRIPTION
**Pull request by rogeriochaves**
Fix some issues on the teether library

### CODE REVIEW

**Comment by wpwood** [comment]
* Tether

**Comment by rogeriochaves** [comment]
@wpwood fixed :P

**Comment by wpwood** [comment]
@rogeriochaves Thanks :smiley: 

:sake: :sushi:

**Comment by wpwood** [comment]
@adampickeral will probably tell you to squash the commits and follow the commit message guidelines before you merge

**Comment by adampickeral** [comment]
looks good, as bill mentioned, squash those commits into one and follow the commit guidelines here https://github.com/rackerlabs/canon-react/blob/master/CONTRIBUTING.md

i'll merge this and create a new release once you've done that

**Pull request merged**
