### PR TITLE
chore: upgrade react version

### PR DESCRIPTION
**Pull request by rogeriochaves**
now to v15.0.1, this was simpler since most work was done when upgrading to 0.14

the final bundle code didn't change one bit, only fixes to specs were made to cope with v15, so everybody working with 0.14 should also be able to work with this one

### CODE REVIEW

**Comment by adampickeral** [comment]
:+1:

**Comment by j00k** [comment]
:clap:

**Comment by OneTechieMom** [comment]
Any chance we can get this merged?

**Comment by adampickeral** [comment]
@OneTechieMom you shouldn't need this to be merged for canon-react to work with react v15

**Comment by OneTechieMom** [comment]
I ended up upgrading to 15.0.1 since it doesn't have the unknown props issue but has the feature I need. Would like to get canon-react on the same version of react.

**Comment by adampickeral** [comment]
we support the two most recent major versions of react, and right now we're able to do that without a branch in canon-react because react 0.14 compatible code is compatible with react 15 compatible code. So until react v16 comes out, we won't be bumping the required react version of canon-react (doing so would force all consumers of canon-react to upgrade to react v15 to get new features).

**Comment by adampickeral** [comment]
upgraded in a separate PR

**Pull request closed without merging**
