### PR TITLE
feat(automation): add a script to automatically create a new release

### PR DESCRIPTION
**Pull request by willcumbie**
Also updated documentation. I'm leaving it in three parts deliberately, since each step requires different permissions.

### CODE REVIEW

**Comment by adampickeral** [comment]
do you think we could combine steps `2` and `3` into a single script?

**Comment by willcumbie** [comment]
@adampickeral We could, and it would be easy, but they do require different permissions. I'm thinking of  a scenario where someone with Github write permissions runs the two scripts, and then has someone else publish to npm for them. (This would also be useful if npm were temporarily down, or someone's account were having temporary problems.)

**Comment by adampickeral** [comment]
@willcumbie good points. :+1:

**Comment by akrikos** [comment]
Does it feel odd to anyone else that the instructions are to publish to npm before github? I may be splitting hairs here, but I've always viewed npm as needing to mirror github even though I know they use different artifacts.

**Comment by willcumbie** [comment]
Yeah, that was in the instructions as I received them, and I thought it was a bit odd. I'll switch the order in the docs.

**Comment by akrikos** [comment]
Assuming it works :+1:

**Pull request merged**
